# Generated by Django 2.1.5 on 2019-01-18 22:59

from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shopuser',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to='shops.Shops'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to='shops.User'),
        ),
        migrations.AlterUniqueTogether(
            name='shopuser',
            unique_together={('shop', 'user')},
        ),
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
        migrations.RemoveField(
            model_name='User',
            name='shops',
        ),
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(related_name='users', through='shops.ShopUser', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.upload_posters_to),
        ),
    ]
