# Generated by Django 2.1.5 on 2019-01-19 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20190118_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='disliked_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
    ]
