# Generated by Django 2.1.5 on 2019-01-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
